---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname frigate
  namespace: flux-system
spec:
  targetNamespace: home-automation
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 30m
  path: ./kubernetes/main/apps/home-automation/frigate/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  dependsOn:
    - name: multus-config
    - name: intel-device-plugins-gpu
    - name: rook-ceph-cluster
    - name: volsync
    - name: external-secrets-stores
  postBuild:
    substitute:
      APP: *appname
      APP_UID: "2000"
      APP_GID: "1800"
      VOLSYNC_CLAIM: frigate-config
      VOLSYNC_CAPACITY: 5Gi
  wait: false
  retryInterval: 1m
  timeout: 5m
