# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: qbtools-secret
stringData:
    config.yaml: ENC[AES256_GCM,data:/MPa,iv:eYwch8z4TtzHiLB6c4bxckWyyLeoVhpwOxn+N1epy4Y=,tag:IbCYu5BexWgIXT2UJKCHOg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12z8sxnrr3qpge7shgx7cpz8d9l83tc0mvvhu9l9jgdrssp8g5acq6uaf7w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQUDFETlRKZ05JaVRWSHhz
            ZTVLL0wwR2V2aHVhZWFaM1NxQjdnem50aFNzCmkzempoUWYrUUpCNFdoMFJGNFo0
            M1Jwa0tUaEZ2NTlwNHZhNGIvUWRJTkkKLS0tIFRPNldUeU9HZ1ZyV2NnQUl4RXVH
            VFNrM2QzK0k4cGFGUnFhbEhIeCtLbmMKGon2re/kefN+6HiVZZRYtfYY0inuHQOw
            xP0COaY0MqHs3IO/IXzY6N0zDhfgAt8RMCLzO6ATD+/tGkfNS5TeZw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rhc7lprjfcfl2uyjxcc0nny7h0ha0l7uykvah0vmcf2s7hecp94qupxyym
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1RytnZGNPOEVBSXk4SGpQ
            M0RpeEtSMTYvQlFWUFdBbHhrTGRjSEdlUEJVCnZRcTFIdy94YlliUnRmd2RSQno4
            SHhmTjZXeXV5bTRaRlVtTCtON3N0SUkKLS0tIGQvUTV2MHBYSy9uY2txeGFnWUt5
            V1Ivemt6dVpPQjZMMUJ5V0RmTWR6aHcKnYwz+0AZQA3givmnlPSA9wSIuFTGCdyW
            fvLmPai78s71Q/+adFLv79y/+SyXpe7W1BEMQqVfFIs8F5d4/I3/vA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-01T21:06:00Z"
    mac: ENC[AES256_GCM,data:g9yMf2a//sh5mEVyp3fl5Qp9iKhb7l2Edh7H0ZOyjvZCj2ifxs1q6FxKkiAzE0uyDs9gHjyvcZC69v8TIf3jr+03a76/jceJvk9Nzj/OmJbGAgMHUbdWwrz81+mugy4zDgGvmGJ8WBc0WN4E31VKZa/lIg0eGBgyYngX+JLGLyo=,iv:2ErjlDBJdNQJsEF+V6XMmolcP/zUUn6C1m9yzEnVTJk=,tag:Y7ze5Po9HEBZyTono6QfLQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
