---
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-shell
  namespace: default
spec:
  terminationGracePeriodSeconds: 5
  # nodeName: k8s-5
  containers:
    - name: shell
      image: ghcr.io/aarnaud/talos-debug-tools:latest-6.6.29
      tty: true
      stdin: true
      securityContext:
        privileged: true
      # volumeMounts:
      # - mountPath: /mnt/host_var
      #   name: host-var
      # - mountPath: /config
      #   name: config
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
        limits:
          cpu: 4000m
          memory: 16Gi
  # volumes:
  # - name: host-var
  #   hostPath:
  #     path: /var
  # - name: config
  #   persistentVolumeClaim:
  #     claimName: frigate-config
