apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-secret
stringData:
    token: ENC[AES256_GCM,data:XLWOlxXXcXgEvw6v+ojGQqVsgkgZANdOgoNMILdSb3cukTum+bL/X6QpV0nZh47BeUba3WdXfiVtzuhUl17PxASTx0fu1GPLRa9UdaWEGISg2+pEJp476ONynJyxPVtZsVtw3UWF3yy3p7x1DziiEQTQ/cNLnC4iyMggkj+M1oLTa8P/qhdk3iOtxdfOZ1jw4o7D3rLTCGop3evYXIQeyt/o4oEwb0VRef2sR3qVj5nCEByySGgV4s684L/csCPBurdOOW0vi7lxp+Z4HrfcsDX4cOnmLIpdt1bPM9a+B6qok2rM0AnaWb2c9nnnQtCZQjOlWlf6ljtsiLVJ8BOWSdrdlBZl3UfkSyi8UgFea8ur723845N2cQrbmr8h2SPt6+8+ACxl/qgd5rP0avDm74ML1jSzXRN60xCutwkQzUCt5vPM+w50OAlF2aVmYXGV9iTd2TLXrP3tmcw1VRcrRLsKLwoiXtIEZiQtvxgHd7eO5uhGSqE7kzY8RmLmiWAa/ZlopnBTJ/mxI7anVsdB6m2UkzqLXZnEXV6u8G1e+RW6scPm3OOPnv4/Dt+GIQ3quTGPiw/6K9D7OdR3XqtOMDELZ2KuaT2iiOoh7WlVUDbvElHRmbRGUQMip6iI4Y5UpbdzAa5tRkBwXQ7cGgH9xgl4ee4L4evZ+Hyhs4W5fvXB1UkQdDGJ+psNZjJfVkPOx7tjLc6SpkOk/xe5xFdPVFGoIjmYXle3UCxQUY/33cw/XV/V7pNRWq5V5nayEslgAiRKWrydr6E3bHDd3J3UkoMLOPgt/1VOb6pb7uCng3pEHFJDHpQ4t7oMSDtJmjIDeCLgKNflnudmratwT8p57Rp4,iv:rNFAASCbun+yhGmt3IHlNkNS++EVapEK3GCczVpGOUU=,tag:1ijluIjVHN4OVOWT2l9trw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12z8sxnrr3qpge7shgx7cpz8d9l83tc0mvvhu9l9jgdrssp8g5acq6uaf7w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2V2NJOVUvTDQ2bHVUL2p6
            TGRFc3lPTzA3b0tqMlU4Tkd5NUdaWW9IdHlVCjdBTnNyTlFiWkRid05Fb1c1dXNo
            QklXbHR0YWxad3hKSzNjb1NhdmdQQVUKLS0tIFIrVkxWOHN4N1pSZjAvOUo1U2xR
            NFMyTHlPUGFnRStjZ2xFU08va3FPMmMK80d9xTPlDAzRLCZ/VOEDMeJAPmO2MTFi
            zJTH7c/8PU4nh8l6TUJIg+N29rvJo+D0zx1kqq2ArT2xfBeOUXbAPg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rhc7lprjfcfl2uyjxcc0nny7h0ha0l7uykvah0vmcf2s7hecp94qupxyym
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWcXA5U0J1djZmc2JjSlps
            Y1oxUloyTWhGQmVtVFpLM3M1cTdmZXVzR0VrCmcrVmMyVU1aQnE4ZkxuZlZoRjBa
            WHdiR01rMSs0Ky9ldHhTZGZpN2I5dE0KLS0tIHJNNlBaZ21Dc1dZNEdQSnpWMktU
            cVJraVY5U2E2ZW12Nk9uRllIcW91QkUKC0O3V9DyHU9SrJdcWfrZEWedcF0OU11/
            3t0ST1BjgRiYtsNff56y4VnOb5kH1hQlC5Zu7wcXePm9G/qcOoEFyQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-31T11:36:35Z"
    mac: ENC[AES256_GCM,data:md//A9xY9mrMEWlttdUpYO/MfCLikte18QJVYxapP0YJr/2f22h8bokXS+sQ/C/9iadZbIeTH9j4WbyBsbgsr7BqGw54IDtPOQIDANYqaZlDyWxrQpKvGAhWJIWMgQYKGM9L3D35bxN4xz7xOHysyELTjNyJ9+Wb4Zb7RrRzwXo=,iv:CNi68Eq3PcideenlTx53zXAZ2xYeckvligHr1lA2qwQ=,tag:0bfvH8srcg4vUODoszhfFQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
